### ISSUE TITLE
Export Modal

### ISSUE THREAD

**Issue by robertlong** [MozillaReality/Spoke#42]
- [ ] ~Author info~ (Moved to #220)
- [ ] ~Copyright / license info~ (Moved to #216)
- [ ] ~Thumbnail file picker~ (Moved to #223)
- [x] Output directory picker

**Comment by brianpeiris** [comment]
Core work closed in #213
